import type { Platform } from "./types";

export const platforms: Record<string, Platform> = {
  salesforce: {
    id: "salesforce",
    name: "Salesforce CRM",
    category: "crm",
    purpose:
      "Customer relationship management and system of record for customer, account, and pipeline data.",
    capabilities: [
      "Account and contact management",
      "Opportunity and pipeline tracking",
      "Sales and service workflows",
      "Marketing Cloud connectors",
      "Customer record unification",
    ],
    strengths: [
      "Enterprise CRM standard",
      "Rich ecosystem and AppExchange",
      "Deep sales, service, and account workflows",
    ],
    limitations: [
      "Complex to configure at scale",
      "Operational data often siloed from warehouse analytics",
      "Lifecycle activation usually requires additional platforms",
    ],
    useCases: [
      "B2B account and opportunity management",
      "Customer support case routing",
      "CRM-led segmentation and handoffs to marketing systems",
    ],
    integrations: ["Snowflake", "Segment", "Braze", "Salesforce Marketing Cloud", "Hightouch"],
    bestFor: "Enterprise CRM and customer record management",
    typicalUsers: "Sales, customer success, and RevOps teams",
  },
  snowflake: {
    id: "snowflake",
    name: "Snowflake",
    category: "warehouse",
    purpose:
      "Central cloud data warehouse that acts as the enterprise source of truth for customer intelligence.",
    capabilities: [
      "Primary function: unify CRM, product, support, and marketing data into one hub",
      "Unified data storage and modelling",
      "SQL analytics and secure data sharing",
      "Scalable compute and storage",
      "Foundation for activation, AI, and reporting",
    ],
    strengths: [
      "Scales with enterprise data volume",
      "Separates storage and compute",
      "Strong partner and activation ecosystem",
    ],
    limitations: [
      "Requires data modelling expertise",
      "Not a customer-facing activation layer",
      "Cost and governance need ongoing management",
    ],
    useCases: [
      "Customer 360 modelling",
      "Multi-source enterprise data unification",
      "Analytics, scoring, and segmentation models",
    ],
    integrations: ["Salesforce", "Hightouch", "Segment", "Braze", "OpenAI", "Claude"],
    bestFor:
      "Business value: a trusted customer data hub that powers engagement, analytics, AI, and acquisition",
    typicalUsers: "Data engineering, analytics, and lifecycle operations teams",
  },
  hightouch: {
    id: "hightouch",
    name: "Hightouch",
    category: "reverse-etl",
    purpose:
      "Activation layer that syncs warehouse audiences and customer attributes into downstream systems.",
    capabilities: [
      "Primary function: reverse ETL and audience activation from Snowflake",
      "Audience and trait syncing",
      "Identity resolution helpers",
      "Journey and lifecycle triggers",
      "Multi-destination orchestration to engagement, ads, and ops tools",
    ],
    strengths: [
      "Warehouse-native activation",
      "No duplicate customer store required",
      "Strong martech and ops integrations",
    ],
    limitations: [
      "Depends on clean warehouse models",
      "Not a messaging or CRM system",
      "Requires collaboration with data teams",
    ],
    useCases: [
      "Lifecycle segment activation",
      "Churn-risk audience sync",
      "Product usage triggers to engagement platforms",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Iterable", "Segment"],
    bestFor:
      "Business value: turns warehouse intelligence into action across Braze, BI, ads, and operational tools",
    typicalUsers: "Lifecycle marketing, customer success, and data teams",
  },
  braze: {
    id: "braze",
    name: "Braze",
    category: "engagement",
    purpose: "Customer engagement platform that orchestrates lifecycle messaging across owned channels.",
    capabilities: [
      "Primary function: journey orchestration and cross-channel engagement",
      "Email, push, SMS, and in-app messaging",
      "Customer journeys and Canvas orchestration",
      "Personalization using warehouse and AI-enriched traits",
    ],
    strengths: [
      "Modern cross-channel journey builder",
      "Strong lifecycle orchestration",
      "Built for product-led and enterprise engagement teams",
    ],
    limitations: [
      "Requires quality audience and event data",
      "Complex journeys need governance",
      "Reporting often complemented by warehouse analytics",
    ],
    useCases: [
      "Onboarding and activation journeys",
      "Retention and win-back programs",
      "Personalized lifecycle communications",
    ],
    integrations: ["Snowflake", "Hightouch", "Segment", "OpenAI", "Salesforce"],
    bestFor:
      "Business value: delivers personalized lifecycle experiences powered by unified customer data",
    typicalUsers: "Lifecycle marketers, CRM managers, and product marketing teams",
  },
  sfmc: {
    id: "sfmc",
    name: "Salesforce Marketing Cloud",
    category: "legacy-engagement",
    purpose:
      "Enterprise marketing automation platform for email, SMS, journeys, and campaign execution within the Salesforce ecosystem.",
    capabilities: [
      "Email Studio",
      "Mobile Studio for SMS",
      "Journey Builder",
      "Automation Studio",
      "Data extensions and audience management",
    ],
    strengths: [
      "Deep Salesforce CRM integration",
      "Enterprise-grade marketing automation",
      "Familiar to Salesforce-centric organizations",
    ],
    limitations: [
      "Heavier implementation and change cycles",
      "Less agile than modern composable stacks",
      "Data often siloed outside the warehouse",
    ],
    useCases: [
      "Enterprise email and SMS programs",
      "Salesforce-native customer journeys",
      "Centralized campaign execution for large marketing teams",
    ],
    integrations: ["Salesforce CRM", "Snowflake", "MuleSoft"],
    bestFor: "Salesforce-native enterprise marketing automation",
    typicalUsers: "Enterprise marketing operations teams",
  },
  "email-sms": {
    id: "email-sms",
    name: "Email / SMS",
    category: "engagement",
    purpose: "Outbound email and SMS channels that deliver campaign communications to customers.",
    capabilities: [
      "Email message delivery",
      "SMS message delivery",
      "Channel execution within marketing programs",
      "Campaign send orchestration",
    ],
    strengths: [
      "Direct customer communication channels",
      "High reach for lifecycle messaging",
      "Core execution layer in legacy marketing stacks",
    ],
    limitations: [
      "Not a data or orchestration platform on its own",
      "Deliverability and compliance require governance",
      "Personalization depends on upstream audience data",
    ],
    useCases: [
      "Promotional and lifecycle email sends",
      "SMS alerts and campaign messages",
      "Channel delivery within Marketing Cloud journeys",
    ],
    integrations: ["Salesforce Marketing Cloud", "Salesforce CRM"],
    bestFor: "Message delivery in traditional enterprise marketing stacks",
    typicalUsers: "Marketing operations and campaign teams",
  },
  segment: {
    id: "segment",
    name: "Segment",
    category: "cdp",
    purpose: "Customer data collection platform that captures and routes behavioural events.",
    capabilities: [
      "Primary function: event collection and destination routing",
      "Event collection from web, mobile, and backend systems",
      "Identity resolution and audience building",
      "Tracking plan governance",
    ],
    strengths: [
      "Standardises event instrumentation",
      "Broad destination catalog",
      "Strong adoption with product and growth teams",
    ],
    limitations: [
      "Can become costly at scale",
      "Not a warehouse replacement",
      "Requires disciplined tracking plans",
    ],
    useCases: [
      "Product event collection",
      "Real-time event forwarding",
      "Routing behavioural data to warehouse and engagement tools",
    ],
    integrations: ["Snowflake", "Braze", "Iterable", "Google Analytics", "Mixpanel"],
    bestFor: "Customer data collection and event routing",
    typicalUsers: "Product, analytics, and growth engineering teams",
  },
  "product-events": {
    id: "product-events",
    name: "Product Events",
    category: "cdp",
    purpose: "User actions and behavioural tracking generated within your product or application.",
    capabilities: [
      "In-product event capture",
      "Behavioural signal generation",
      "Usage tracking",
      "Feature adoption events",
    ],
    strengths: [
      "Ground-truth product behaviour data",
      "Foundation for PLG lifecycle programs",
      "Enables usage-based segmentation",
    ],
    limitations: [
      "Requires consistent instrumentation",
      "Not useful without downstream routing and storage",
      "Needs governance to avoid event sprawl",
    ],
    useCases: [
      "Activation and onboarding triggers",
      "Feature adoption measurement",
      "Usage-based lifecycle campaigns",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Behavioural signals feeding warehouse-centric lifecycle programs",
    typicalUsers: "Product, growth, and analytics teams",
  },
  "web-events": {
    id: "web-events",
    name: "Web Events",
    category: "cdp",
    purpose: "Digital behavioural signals captured from websites and web applications.",
    capabilities: [
      "Primary function: capture web interactions and behavioural events",
      "Page views, clicks, and conversion events",
      "Marketing and product behaviour tracking",
      "Inputs for warehouse customer models",
    ],
    strengths: [
      "Reveals top-of-funnel and in-session behaviour",
      "Supports acquisition and lifecycle analysis",
      "Complements CRM and product data in the hub",
    ],
    limitations: [
      "Requires consistent tagging or instrumentation",
      "Identity stitching needed for cross-channel views",
      "Not an activation platform on its own",
    ],
    useCases: [
      "Web behaviour enrichment in Snowflake",
      "Acquisition and conversion analysis",
      "Lifecycle triggers based on site activity",
    ],
    integrations: ["Snowflake", "Segment", "Google Analytics"],
    bestFor: "Business value: adds digital behaviour context to the customer data hub",
    typicalUsers: "Marketing analytics, growth, and data teams",
  },
  "web-app": {
    id: "web-app",
    name: "Web App",
    category: "cdp",
    purpose: "Product usage and behavioural events generated in the web application.",
    capabilities: [
      "Primary function: capture in-app web product events",
      "Feature usage and activation tracking",
      "Session and funnel events",
      "Inputs for PLG lifecycle programs",
    ],
    strengths: [
      "Ground-truth product usage from web clients",
      "Foundation for onboarding and adoption journeys",
      "Feeds Segment and warehouse models",
    ],
    limitations: [
      "Requires disciplined event taxonomy",
      "Must be unified with mobile and backend events",
      "Not useful without downstream routing",
    ],
    useCases: [
      "Product-qualified lead workflows",
      "Feature adoption campaigns",
      "Usage-based health scoring",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Business value: behavioural intelligence for product-led growth",
    typicalUsers: "Product, growth, and engineering teams",
  },
  "mobile-app": {
    id: "mobile-app",
    name: "Mobile App",
    category: "cdp",
    purpose: "Behavioural events captured from iOS and Android product experiences.",
    capabilities: [
      "Primary function: capture mobile product and engagement events",
      "In-app usage and session tracking",
      "Push and lifecycle interaction events",
      "Mobile-specific behavioural signals",
    ],
    strengths: [
      "Critical for mobile-first SaaS and consumer apps",
      "Enables mobile lifecycle orchestration",
      "Complements web and backend event streams",
    ],
    limitations: [
      "Instrumentation can be harder across app versions",
      "Identity resolution needed across devices",
      "Requires routing through Segment or similar",
    ],
    useCases: [
      "Mobile onboarding journeys",
      "Re-engagement and retention programs",
      "Cross-device customer intelligence",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Business value: mobile behavioural context for lifecycle activation",
    typicalUsers: "Product, mobile engineering, and growth teams",
  },
  "backend-events": {
    id: "backend-events",
    name: "Backend Events",
    category: "cdp",
    purpose: "Server-side product and transaction events emitted from backend systems.",
    capabilities: [
      "Primary function: capture authoritative server-side events",
      "Billing, subscription, and account lifecycle events",
      "Product state changes and system triggers",
      "Reliable event delivery to Segment or warehouse",
    ],
    strengths: [
      "More reliable than client-only tracking",
      "Captures business-critical lifecycle moments",
      "Supports revenue and product intelligence models",
    ],
    limitations: [
      "Requires engineering ownership",
      "Must align with client-side event taxonomy",
      "Not customer-facing on its own",
    ],
    useCases: [
      "Trial-to-paid conversion tracking",
      "Renewal and expansion triggers",
      "Server-validated product usage signals",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Business value: trusted backend signals for lifecycle and revenue programs",
    typicalUsers: "Engineering, data, and lifecycle operations teams",
  },
  "commerce-data": {
    id: "commerce-data",
    name: "Commerce",
    category: "cdp",
    purpose: "Commerce, order, and transaction data describing customer purchasing behaviour.",
    capabilities: [
      "Primary function: capture orders, baskets, and purchase history",
      "Transaction and revenue signals",
      "Product affinity and purchase patterns",
      "Commerce attributes for customer models",
    ],
    strengths: [
      "Connects engagement to commercial outcomes",
      "Improves personalization and recommendations",
      "Critical for retail and D2C customer 360 views",
    ],
    limitations: [
      "Often spread across commerce platforms",
      "Requires normalization in the warehouse",
      "Sensitive data needs governance",
    ],
    useCases: [
      "Post-purchase lifecycle journeys",
      "Cross-sell and replenishment programs",
      "Customer 360 enrichment",
    ],
    integrations: ["Snowflake", "Hightouch", "Braze"],
    bestFor: "Business value: commerce context inside a unified customer view",
    typicalUsers: "Commerce ops, marketing, and data teams",
  },
  "product-usage": {
    id: "product-usage",
    name: "Product Usage",
    category: "cdp",
    purpose: "Product adoption and usage signals that describe how customers use your offering.",
    capabilities: [
      "Primary function: represent product usage in the customer model",
      "Feature adoption and depth-of-use metrics",
      "Health and activation indicators",
      "Usage traits for segmentation",
    ],
    strengths: [
      "Reveals value realization and churn risk",
      "Supports customer success and PLG motions",
      "Enriches customer 360 models",
    ],
    limitations: [
      "Depends on strong instrumentation",
      "Must be joined with CRM and support data",
      "Needs modelling in Snowflake",
    ],
    useCases: [
      "At-risk customer identification",
      "Expansion and upgrade targeting",
      "Customer 360 and success programs",
    ],
    integrations: ["Snowflake", "Segment", "Hightouch", "Braze"],
    bestFor: "Business value: product context for intelligent lifecycle decisions",
    typicalUsers: "Product, customer success, and data teams",
  },
  "marketing-data": {
    id: "marketing-data",
    name: "Marketing",
    category: "cdp",
    purpose: "Marketing interaction and campaign data from engagement and acquisition systems.",
    capabilities: [
      "Primary function: capture marketing engagement history and attributes",
      "Campaign response and channel preferences",
      "Audience and consent attributes",
      "Marketing signals for customer 360 models",
    ],
    strengths: [
      "Improves personalization and frequency management",
      "Connects campaigns to downstream outcomes",
      "Complements CRM and product data in the hub",
    ],
    limitations: [
      "Often fragmented across tools",
      "Requires warehouse modelling for unified use",
      "Consent and privacy rules must be enforced",
    ],
    useCases: [
      "Cross-channel customer 360 views",
      "Audience suppression and preference management",
      "Lifecycle attribution analysis",
    ],
    integrations: ["Snowflake", "Braze", "Hightouch", "Advertising Platforms"],
    bestFor: "Business value: marketing context inside a unified customer intelligence layer",
    typicalUsers: "Lifecycle marketing, CRM, and analytics teams",
  },
  "customer-360": {
    id: "customer-360",
    name: "Customer 360",
    category: "warehouse",
    purpose: "Unified customer view model built in the warehouse from CRM, commerce, support, product, and marketing data.",
    capabilities: [
      "Primary function: create a single trusted customer profile and trait layer",
      "Identity resolution across source systems",
      "Unified traits, segments, and scores",
      "Foundation for activation and analytics",
    ],
    strengths: [
      "Breaks down silos across enterprise systems",
      "Creates one language for customer intelligence",
      "Powers personalization, reporting, and acquisition",
    ],
    limitations: [
      "Requires mature data modelling and governance",
      "Only valuable when sources are integrated into Snowflake",
      "Must be maintained as systems evolve",
    ],
    useCases: [
      "Enterprise customer 360 programs",
      "Cross-functional segmentation and reporting",
      "Trusted activation layer for Hightouch and Braze",
    ],
    integrations: ["Snowflake", "Hightouch", "Braze", "BI Platforms"],
    bestFor: "Business value: one customer view that every team can activate against",
    typicalUsers: "Data, marketing operations, and customer intelligence teams",
  },
  "crm-data": {
    id: "crm-data",
    name: "CRM Data",
    category: "crm",
    purpose: "Customer profiles and account information sourced from CRM systems.",
    capabilities: [
      "Account and contact profiles",
      "Sales and service history",
      "Account hierarchy data",
      "CRM-derived customer attributes",
    ],
    strengths: [
      "Trusted commercial customer record",
      "Rich relationship and account context",
      "Critical for B2B lifecycle programs",
    ],
    limitations: [
      "May lack product usage depth",
      "Often needs enrichment from other sources",
      "Quality depends on CRM hygiene",
    ],
    useCases: [
      "Account-based lifecycle programs",
      "Sales and success-driven segmentation",
      "Enterprise customer intelligence models",
    ],
    integrations: ["Snowflake", "Salesforce CRM", "Hightouch"],
    bestFor: "CRM-led enterprise customer intelligence",
    typicalUsers: "RevOps, marketing operations, and data teams",
  },
  "product-data": {
    id: "product-data",
    name: "Product Data",
    category: "cdp",
    purpose: "Usage and behavioural signals from product interactions.",
    capabilities: [
      "Feature usage events",
      "Activation and adoption signals",
      "In-app behaviour tracking",
      "Product usage traits",
    ],
    strengths: [
      "Reveals real product engagement",
      "Supports PLG and expansion motions",
      "Improves personalization quality",
    ],
    limitations: [
      "Requires strong instrumentation",
      "Must be modelled for enterprise use",
      "Needs identity resolution with CRM data",
    ],
    useCases: [
      "Usage-based health scoring",
      "Expansion and retention triggers",
      "Product-qualified lead workflows",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Behavioural intelligence in enterprise CDP architectures",
    typicalUsers: "Product, growth, and data teams",
  },
  "support-data": {
    id: "support-data",
    name: "Support Data",
    category: "cdp",
    purpose: "Service and customer support interaction data.",
    capabilities: [
      "Support ticket history",
      "Case status and resolution data",
      "Customer effort signals",
      "Service interaction timelines",
    ],
    strengths: [
      "Surfaces customer friction and risk",
      "Improves retention and success programs",
      "Adds operational context to customer models",
    ],
    limitations: [
      "Often siloed in service platforms",
      "Requires normalization for warehouse use",
      "Must be joined with CRM and product data",
    ],
    useCases: [
      "At-risk customer identification",
      "Support-driven retention outreach",
      "Success and service lifecycle programs",
    ],
    integrations: ["Snowflake", "Salesforce CRM", "Hightouch"],
    bestFor: "Service-aware customer intelligence",
    typicalUsers: "Customer success, support operations, and data teams",
  },
  "financial-data": {
    id: "financial-data",
    name: "Financial Data",
    category: "cdp",
    purpose: "Revenue and transaction data used for customer intelligence and lifecycle decisions.",
    capabilities: [
      "Billing and subscription data",
      "Transaction history",
      "Revenue and ARR metrics",
      "Payment and renewal signals",
    ],
    strengths: [
      "Connects engagement to revenue outcomes",
      "Supports expansion and renewal programs",
      "Critical for enterprise customer valuation",
    ],
    limitations: [
      "Sensitive data requires strict governance",
      "Often spread across finance systems",
      "Needs careful modelling in the warehouse",
    ],
    useCases: [
      "Renewal and expansion targeting",
      "High-value customer programs",
      "Revenue-at-risk lifecycle workflows",
    ],
    integrations: ["Snowflake", "Hightouch", "Braze"],
    bestFor: "Revenue-aware lifecycle and customer intelligence programs",
    typicalUsers: "Finance operations, RevOps, and lifecycle teams",
  },
  "ai-services": {
    id: "ai-services",
    name: "OpenAI / Claude",
    category: "ai",
    purpose:
      "AI services that enhance personalization, content, segmentation, and decision support across the lifecycle. Braze remains the engagement platform — AI improves experiences rather than replacing the engagement layer.",
    capabilities: [
      "Content generation",
      "Personalization",
      "Recommendations",
      "AI-assisted segmentation",
      "Customer insights",
      "Intelligent decision support",
    ],
    strengths: [
      "Accelerates content and journey creation",
      "Improves relevance at scale",
      "Supports intelligent automation without replacing core martech",
    ],
    limitations: [
      "Requires guardrails and human review",
      "Not a data, messaging, or CRM platform",
      "Quality depends on context, prompts, and upstream data",
    ],
    useCases: [
      "Personalized message drafting",
      "Next-best-action recommendations",
      "AI-assisted audience and journey design",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Hightouch"],
    bestFor: "AI-enhanced lifecycle personalization and automation",
    typicalUsers: "Lifecycle marketing, product, and AI operations teams",
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    purpose:
      "AI models that enrich warehouse customer data and support segmentation, personalization, content, and insights.",
    capabilities: [
      "Primary function: AI enrichment alongside Snowflake customer data",
      "Content generation and personalization",
      "Recommendations and AI-assisted segmentation",
      "Customer insights and intelligent decision support",
    ],
    strengths: [
      "Broad model capability",
      "Strong ecosystem adoption",
      "Flexible API integration patterns",
    ],
    limitations: [
      "Requires guardrails and governance",
      "Not a data or messaging platform",
      "Quality depends on context and prompts",
    ],
    useCases: [
      "Personalised message drafting",
      "Journey content optimisation",
      "Customer insight generation",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Hightouch"],
    bestFor:
      "Business value: AI-enhanced customer intelligence without replacing the engagement layer",
    typicalUsers: "Product, lifecycle ops, and AI engineering teams",
  },
  claude: {
    id: "claude",
    name: "Claude",
    category: "ai",
    purpose:
      "AI assistant that enriches warehouse data with reasoning, insights, segmentation support, and content refinement.",
    capabilities: [
      "Primary function: AI enrichment alongside Snowflake customer data",
      "Long-context analysis of customer and journey data",
      "Content refinement and structured insights",
      "AI-assisted segmentation and recommendations",
    ],
    strengths: [
      "Strong reasoning quality",
      "Useful for operational and strategic analysis",
      "Good for structured outputs",
    ],
    limitations: [
      "Requires integration layer",
      "Not a customer data system",
      "Needs human review in production workflows",
    ],
    useCases: [
      "Lifecycle strategy analysis",
      "Campaign copy refinement",
      "AI-assisted segmentation and insights",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce"],
    bestFor:
      "Business value: reasoning-heavy AI enrichment that supports Braze-led engagement",
    typicalUsers: "Lifecycle leaders and marketing operations teams",
  },
  "bi-platforms": {
    id: "bi-platforms",
    name: "BI Platforms",
    category: "analytics",
    purpose: "Reporting and analytics layer for business intelligence and performance visibility.",
    capabilities: [
      "Primary function: enterprise reporting and analytics on warehouse data",
      "Dashboards and KPI tracking",
      "Self-serve analytics for business teams",
      "Lifecycle and marketing performance reporting",
    ],
    strengths: [
      "Makes warehouse data accessible to business teams",
      "Supports cross-functional visibility",
      "Complements engagement and activation layers",
    ],
    limitations: [
      "Not a real-time activation platform",
      "Depends on curated data models",
      "Reporting lag may vary by stack",
    ],
    useCases: [
      "Marketing and lifecycle performance reporting",
      "Customer intelligence dashboards",
      "Executive reporting on engagement outcomes",
    ],
    integrations: ["Snowflake", "Hightouch", "Google Analytics"],
    bestFor: "Business value: turns unified customer data into stakeholder reporting and insight",
    typicalUsers: "Analytics, marketing operations, and business teams",
  },
  "advertising-platforms": {
    id: "advertising-platforms",
    name: "Advertising Platforms",
    category: "analytics",
    categoryLabel: "Paid Media",
    purpose: "Paid media and advertising platforms for audience activation and acquisition.",
    capabilities: [
      "Primary function: activate warehouse audiences in paid media channels",
      "Retargeting and lookalike audience sync",
      "Acquisition campaign activation",
      "Paid media audience orchestration",
    ],
    strengths: [
      "Extends customer intelligence into acquisition",
      "Supports growth and demand generation",
      "Connects lifecycle data to paid media",
    ],
    limitations: [
      "Requires privacy and consent governance",
      "Not an owned-channel engagement platform",
      "Performance depends on audience quality",
    ],
    useCases: [
      "Retargeting and reactivation campaigns",
      "Lookalike acquisition programs",
      "Paid media audience activation from warehouse segments",
    ],
    integrations: ["Snowflake", "Hightouch", "Google Analytics"],
    bestFor: "Business value: extends customer intelligence into acquisition and paid growth",
    typicalUsers: "Growth, demand generation, and marketing analytics teams",
  },
  iterable: {
    id: "iterable",
    name: "Iterable",
    category: "engagement",
    purpose: "Cross-channel marketing platform focused on growth and lifecycle experimentation.",
    capabilities: [
      "Email and push campaigns",
      "Workflow Studio",
      "Experiments and A/B testing",
      "Catalog and personalisation",
      "SMS and in-app",
    ],
    strengths: [
      "Strong experimentation tooling",
      "Growth-team friendly UX",
      "Flexible workflow builder",
    ],
    limitations: [
      "Less enterprise CRM depth than Salesforce stack",
      "Warehouse activation usually needs middleware",
      "Complexity grows with journey count",
    ],
    useCases: [
      "Growth lifecycle programs",
      "Promotional campaign orchestration",
      "Product-led onboarding experiments",
    ],
    integrations: ["Segment", "Snowflake", "Hightouch", "Salesforce"],
    bestFor: "Growth and experimentation-led lifecycle teams",
    typicalUsers: "Growth marketing and CRM teams",
  },
  mparticle: {
    id: "mparticle",
    name: "mParticle",
    category: "cdp",
    purpose: "Enterprise customer data platform for real-time data collection and audience orchestration.",
    capabilities: [
      "Real-time event ingestion",
      "Audience segmentation",
      "Identity graph",
      "Partner integrations",
      "Data quality controls",
    ],
    strengths: [
      "Enterprise-grade CDP",
      "Strong mobile and app focus",
      "Real-time activation paths",
    ],
    limitations: [
      "Higher implementation overhead",
      "Premium pricing tier",
      "Requires cross-team alignment",
    ],
    useCases: [
      "Mobile-first customer data unification",
      "Real-time audience activation",
      "Cross-channel identity management",
    ],
    integrations: ["Braze", "Snowflake", "Salesforce", "Google Analytics"],
    bestFor: "Enterprise CDP and real-time activation",
    typicalUsers: "Enterprise marketing and data platform teams",
  },
  "google-analytics": {
    id: "google-analytics",
    name: "Google Analytics",
    category: "analytics",
    purpose: "Web and app analytics for understanding acquisition, behaviour, and conversion performance.",
    capabilities: [
      "Traffic analytics",
      "Conversion tracking",
      "Audience reporting",
      "Funnel analysis",
      "Campaign attribution",
    ],
    strengths: [
      "Ubiquitous web analytics standard",
      "Easy initial setup",
      "Strong marketing reporting",
    ],
    limitations: [
      "Limited warehouse-native depth",
      "Identity gaps across devices",
      "Not an activation platform",
    ],
    useCases: [
      "Website performance tracking",
      "Campaign measurement",
      "Top-of-funnel behaviour analysis",
    ],
    integrations: ["Segment", "Snowflake", "Braze", "Google Ads"],
    bestFor: "Digital analytics and acquisition reporting",
    typicalUsers: "Marketing analytics and growth teams",
  },
  mixpanel: {
    id: "mixpanel",
    name: "Mixpanel",
    category: "analytics",
    purpose: "Product analytics platform focused on user behaviour, retention, and funnel performance.",
    capabilities: [
      "Event-based analytics",
      "Retention analysis",
      "Funnel reporting",
      "Cohort exploration",
      "Experiment measurement",
    ],
    strengths: [
      "Product-team friendly analytics",
      "Strong behavioural insights",
      "Fast time-to-value for product teams",
    ],
    limitations: [
      "Not a messaging or CRM tool",
      "Warehouse integration varies by setup",
      "Requires disciplined event taxonomy",
    ],
    useCases: [
      "Feature adoption analysis",
      "Retention and churn diagnostics",
      "Experiment readouts",
    ],
    integrations: ["Segment", "Snowflake", "Braze", "Iterable"],
    bestFor: "Product-led growth analytics",
    typicalUsers: "Product managers and growth analysts",
  },
  customer: {
    id: "customer",
    name: "Customer",
    category: "customer",
    purpose: "End user or customer receiving personalized lifecycle experiences and communications.",
    capabilities: [
      "Receives email, push, SMS, and in-app messages",
      "Experiences onboarding and retention journeys",
      "Interacts with product and support touchpoints",
    ],
    strengths: [
      "Central outcome of the architecture",
      "Benefits from unified data and orchestration",
    ],
    limitations: [
      "Experience quality depends on upstream stack quality",
      "Fragmented data creates inconsistent journeys",
    ],
    useCases: [
      "Onboarding and activation",
      "Renewal and expansion",
      "Support and success engagement",
    ],
    integrations: ["All upstream platforms"],
    bestFor: "Delivering cohesive lifecycle experiences",
    typicalUsers: "Every customer and user of your product",
  },
};

export const platformList = Object.values(platforms);

export function getPlatform(id: string): Platform | undefined {
  return platforms[id];
}
