import type { Platform } from "./types";

export const platforms: Record<string, Platform> = {
  salesforce: {
    id: "salesforce",
    name: "Salesforce CRM",
    category: "crm",
    purpose:
      "Customer relationship management and system of record for customer, account, and pipeline data.",
    capabilities: [
      "Account and contact management",
      "Opportunity and pipeline tracking",
      "Sales and service workflows",
      "Marketing Cloud connectors",
      "Customer record unification",
    ],
    strengths: [
      "Enterprise CRM standard",
      "Rich ecosystem and AppExchange",
      "Deep sales, service, and account workflows",
    ],
    limitations: [
      "Complex to configure at scale",
      "Operational data often siloed from warehouse analytics",
      "Lifecycle activation usually requires additional platforms",
    ],
    useCases: [
      "B2B account and opportunity management",
      "Customer support case routing",
      "CRM-led segmentation and handoffs to marketing systems",
    ],
    integrations: ["Snowflake", "Segment", "Braze", "Salesforce Marketing Cloud", "Hightouch"],
    bestFor: "Enterprise CRM and customer record management",
    typicalUsers: "Sales, customer success, and RevOps teams",
  },
  snowflake: {
    id: "snowflake",
    name: "Snowflake",
    category: "warehouse",
    purpose: "Centralized cloud data warehouse and single source of truth for enterprise customer data.",
    capabilities: [
      "Unified data storage",
      "SQL analytics",
      "Secure data sharing",
      "Scalable compute and storage",
      "Role-based access control",
    ],
    strengths: [
      "Scales with enterprise data volume",
      "Separates storage and compute",
      "Strong partner and activation ecosystem",
    ],
    limitations: [
      "Requires data modelling expertise",
      "Not a customer-facing activation layer",
      "Cost and governance need ongoing management",
    ],
    useCases: [
      "Customer 360 modelling",
      "Multi-source enterprise data unification",
      "Analytics, scoring, and segmentation models",
    ],
    integrations: ["Salesforce", "Hightouch", "Segment", "Braze", "OpenAI", "Claude"],
    bestFor: "Modern analytics and enterprise data foundations",
    typicalUsers: "Data engineering, analytics, and lifecycle operations teams",
  },
  hightouch: {
    id: "hightouch",
    name: "Hightouch",
    category: "reverse-etl",
    purpose:
      "Reverse ETL and customer activation platform that syncs warehouse data into downstream business systems.",
    capabilities: [
      "Reverse ETL pipelines",
      "Audience and trait syncing",
      "Identity resolution helpers",
      "Journey and lifecycle triggers",
      "Operational workflow activation",
    ],
    strengths: [
      "Warehouse-native activation",
      "No duplicate customer store required",
      "Strong martech and ops integrations",
    ],
    limitations: [
      "Depends on clean warehouse models",
      "Not a messaging or CRM system",
      "Requires collaboration with data teams",
    ],
    useCases: [
      "Lifecycle segment activation",
      "Churn-risk audience sync",
      "Product usage triggers to engagement platforms",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Iterable", "Segment"],
    bestFor: "Connecting warehouse data to engagement and operations",
    typicalUsers: "Lifecycle marketing, customer success, and data teams",
  },
  braze: {
    id: "braze",
    name: "Braze",
    category: "engagement",
    purpose:
      "Customer engagement platform for email, push, SMS, in-app messaging, and journey orchestration.",
    capabilities: [
      "Email",
      "Push notifications",
      "SMS",
      "In-app messaging",
      "Customer journeys and Canvas orchestration",
    ],
    strengths: [
      "Modern cross-channel journey builder",
      "Strong lifecycle orchestration",
      "Built for product-led and enterprise engagement teams",
    ],
    limitations: [
      "Requires quality audience and event data",
      "Complex journeys need governance",
      "Reporting often complemented by warehouse analytics",
    ],
    useCases: [
      "Onboarding and activation journeys",
      "Retention and win-back programs",
      "Personalized lifecycle communications",
    ],
    integrations: ["Snowflake", "Hightouch", "Segment", "OpenAI", "Salesforce"],
    bestFor: "Modern lifecycle marketing and customer engagement",
    typicalUsers: "Lifecycle marketers, CRM managers, and product marketing teams",
  },
  sfmc: {
    id: "sfmc",
    name: "Salesforce Marketing Cloud",
    category: "legacy-engagement",
    purpose:
      "Enterprise marketing automation platform for email, SMS, journeys, and campaign execution within the Salesforce ecosystem.",
    capabilities: [
      "Email Studio",
      "Mobile Studio for SMS",
      "Journey Builder",
      "Automation Studio",
      "Data extensions and audience management",
    ],
    strengths: [
      "Deep Salesforce CRM integration",
      "Enterprise-grade marketing automation",
      "Familiar to Salesforce-centric organizations",
    ],
    limitations: [
      "Heavier implementation and change cycles",
      "Less agile than modern composable stacks",
      "Data often siloed outside the warehouse",
    ],
    useCases: [
      "Enterprise email and SMS programs",
      "Salesforce-native customer journeys",
      "Centralized campaign execution for large marketing teams",
    ],
    integrations: ["Salesforce CRM", "Snowflake", "MuleSoft"],
    bestFor: "Salesforce-native enterprise marketing automation",
    typicalUsers: "Enterprise marketing operations teams",
  },
  "email-sms": {
    id: "email-sms",
    name: "Email / SMS",
    category: "engagement",
    purpose: "Outbound email and SMS channels that deliver campaign communications to customers.",
    capabilities: [
      "Email message delivery",
      "SMS message delivery",
      "Channel execution within marketing programs",
      "Campaign send orchestration",
    ],
    strengths: [
      "Direct customer communication channels",
      "High reach for lifecycle messaging",
      "Core execution layer in legacy marketing stacks",
    ],
    limitations: [
      "Not a data or orchestration platform on its own",
      "Deliverability and compliance require governance",
      "Personalization depends on upstream audience data",
    ],
    useCases: [
      "Promotional and lifecycle email sends",
      "SMS alerts and campaign messages",
      "Channel delivery within Marketing Cloud journeys",
    ],
    integrations: ["Salesforce Marketing Cloud", "Salesforce CRM"],
    bestFor: "Message delivery in traditional enterprise marketing stacks",
    typicalUsers: "Marketing operations and campaign teams",
  },
  segment: {
    id: "segment",
    name: "Segment",
    category: "cdp",
    purpose: "Customer data collection and event routing platform for product and marketing systems.",
    capabilities: [
      "Event collection",
      "Identity resolution",
      "Audience building",
      "Destination routing",
      "Tracking plan governance",
    ],
    strengths: [
      "Standardises event instrumentation",
      "Broad destination catalog",
      "Strong adoption with product and growth teams",
    ],
    limitations: [
      "Can become costly at scale",
      "Not a warehouse replacement",
      "Requires disciplined tracking plans",
    ],
    useCases: [
      "Product event collection",
      "Real-time event forwarding",
      "Routing behavioural data to warehouse and engagement tools",
    ],
    integrations: ["Snowflake", "Braze", "Iterable", "Google Analytics", "Mixpanel"],
    bestFor: "Customer data collection and event routing",
    typicalUsers: "Product, analytics, and growth engineering teams",
  },
  "product-events": {
    id: "product-events",
    name: "Product Events",
    category: "cdp",
    purpose: "User actions and behavioural tracking generated within your product or application.",
    capabilities: [
      "In-product event capture",
      "Behavioural signal generation",
      "Usage tracking",
      "Feature adoption events",
    ],
    strengths: [
      "Ground-truth product behaviour data",
      "Foundation for PLG lifecycle programs",
      "Enables usage-based segmentation",
    ],
    limitations: [
      "Requires consistent instrumentation",
      "Not useful without downstream routing and storage",
      "Needs governance to avoid event sprawl",
    ],
    useCases: [
      "Activation and onboarding triggers",
      "Feature adoption measurement",
      "Usage-based lifecycle campaigns",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Product-led growth and behavioural lifecycle programs",
    typicalUsers: "Product, growth, and analytics teams",
  },
  "crm-data": {
    id: "crm-data",
    name: "CRM Data",
    category: "crm",
    purpose: "Customer profiles and account information sourced from CRM systems.",
    capabilities: [
      "Account and contact profiles",
      "Sales and service history",
      "Account hierarchy data",
      "CRM-derived customer attributes",
    ],
    strengths: [
      "Trusted commercial customer record",
      "Rich relationship and account context",
      "Critical for B2B lifecycle programs",
    ],
    limitations: [
      "May lack product usage depth",
      "Often needs enrichment from other sources",
      "Quality depends on CRM hygiene",
    ],
    useCases: [
      "Account-based lifecycle programs",
      "Sales and success-driven segmentation",
      "Enterprise customer intelligence models",
    ],
    integrations: ["Snowflake", "Salesforce CRM", "Hightouch"],
    bestFor: "CRM-led enterprise customer intelligence",
    typicalUsers: "RevOps, marketing operations, and data teams",
  },
  "product-data": {
    id: "product-data",
    name: "Product Data",
    category: "cdp",
    purpose: "Usage and behavioural signals from product interactions.",
    capabilities: [
      "Feature usage events",
      "Activation and adoption signals",
      "In-app behaviour tracking",
      "Product usage traits",
    ],
    strengths: [
      "Reveals real product engagement",
      "Supports PLG and expansion motions",
      "Improves personalization quality",
    ],
    limitations: [
      "Requires strong instrumentation",
      "Must be modelled for enterprise use",
      "Needs identity resolution with CRM data",
    ],
    useCases: [
      "Usage-based health scoring",
      "Expansion and retention triggers",
      "Product-qualified lead workflows",
    ],
    integrations: ["Segment", "Snowflake", "Braze"],
    bestFor: "Behavioural intelligence in enterprise CDP architectures",
    typicalUsers: "Product, growth, and data teams",
  },
  "support-data": {
    id: "support-data",
    name: "Support Data",
    category: "cdp",
    purpose: "Service and customer support interaction data.",
    capabilities: [
      "Support ticket history",
      "Case status and resolution data",
      "Customer effort signals",
      "Service interaction timelines",
    ],
    strengths: [
      "Surfaces customer friction and risk",
      "Improves retention and success programs",
      "Adds operational context to customer models",
    ],
    limitations: [
      "Often siloed in service platforms",
      "Requires normalization for warehouse use",
      "Must be joined with CRM and product data",
    ],
    useCases: [
      "At-risk customer identification",
      "Support-driven retention outreach",
      "Success and service lifecycle programs",
    ],
    integrations: ["Snowflake", "Salesforce CRM", "Hightouch"],
    bestFor: "Service-aware customer intelligence",
    typicalUsers: "Customer success, support operations, and data teams",
  },
  "financial-data": {
    id: "financial-data",
    name: "Financial Data",
    category: "cdp",
    purpose: "Revenue and transaction data used for customer intelligence and lifecycle decisions.",
    capabilities: [
      "Billing and subscription data",
      "Transaction history",
      "Revenue and ARR metrics",
      "Payment and renewal signals",
    ],
    strengths: [
      "Connects engagement to revenue outcomes",
      "Supports expansion and renewal programs",
      "Critical for enterprise customer valuation",
    ],
    limitations: [
      "Sensitive data requires strict governance",
      "Often spread across finance systems",
      "Needs careful modelling in the warehouse",
    ],
    useCases: [
      "Renewal and expansion targeting",
      "High-value customer programs",
      "Revenue-at-risk lifecycle workflows",
    ],
    integrations: ["Snowflake", "Hightouch", "Braze"],
    bestFor: "Revenue-aware lifecycle and customer intelligence programs",
    typicalUsers: "Finance operations, RevOps, and lifecycle teams",
  },
  "ai-services": {
    id: "ai-services",
    name: "OpenAI / Claude",
    category: "ai",
    purpose:
      "AI services that enhance personalization, content, segmentation, and decision support across the lifecycle. Braze remains the engagement platform — AI improves experiences rather than replacing the engagement layer.",
    capabilities: [
      "Content generation",
      "Personalization",
      "Recommendations",
      "AI-assisted segmentation",
      "Customer insights",
      "Intelligent decision support",
    ],
    strengths: [
      "Accelerates content and journey creation",
      "Improves relevance at scale",
      "Supports intelligent automation without replacing core martech",
    ],
    limitations: [
      "Requires guardrails and human review",
      "Not a data, messaging, or CRM platform",
      "Quality depends on context, prompts, and upstream data",
    ],
    useCases: [
      "Personalized message drafting",
      "Next-best-action recommendations",
      "AI-assisted audience and journey design",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Hightouch"],
    bestFor: "AI-enhanced lifecycle personalization and automation",
    typicalUsers: "Lifecycle marketing, product, and AI operations teams",
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    purpose:
      "AI models for content generation, personalization, recommendations, segmentation support, and intelligent decision-making.",
    capabilities: [
      "LLM content generation",
      "Classification and tagging",
      "Summarisation",
      "Embeddings and retrieval",
      "Agent-style workflows",
    ],
    strengths: [
      "Broad model capability",
      "Strong ecosystem adoption",
      "Flexible API integration patterns",
    ],
    limitations: [
      "Requires guardrails and governance",
      "Not a data or messaging platform",
      "Quality depends on context and prompts",
    ],
    useCases: [
      "Personalised message drafting",
      "Journey content optimisation",
      "Customer insight generation",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Hightouch"],
    bestFor: "AI-assisted lifecycle content and intelligence",
    typicalUsers: "Product, lifecycle ops, and AI engineering teams",
  },
  claude: {
    id: "claude",
    name: "Claude",
    category: "ai",
    purpose:
      "AI assistant for reasoning-heavy lifecycle tasks such as journey analysis, copy refinement, insights, and decision support.",
    capabilities: [
      "Long-context reasoning",
      "Structured analysis",
      "Content refinement",
      "Workflow assistance",
      "Document summarisation",
    ],
    strengths: [
      "Strong reasoning quality",
      "Useful for operational and strategic analysis",
      "Good for structured outputs",
    ],
    limitations: [
      "Requires integration layer",
      "Not a customer data system",
      "Needs human review in production workflows",
    ],
    useCases: [
      "Lifecycle strategy analysis",
      "Campaign copy refinement",
      "AI-assisted segmentation and insights",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce"],
    bestFor: "AI-assisted strategy, insights, and operations",
    typicalUsers: "Lifecycle leaders and marketing operations teams",
  },
  "bi-platforms": {
    id: "bi-platforms",
    name: "BI Platforms",
    category: "analytics",
    purpose: "Reporting and analytics for business intelligence, performance measurement, and stakeholder visibility.",
    capabilities: [
      "Dashboards and reporting",
      "Self-serve analytics",
      "Metric definitions and KPI tracking",
      "Executive and team reporting",
    ],
    strengths: [
      "Makes warehouse data accessible to business teams",
      "Supports cross-functional visibility",
      "Complements engagement and activation layers",
    ],
    limitations: [
      "Not a real-time activation platform",
      "Depends on curated data models",
      "Reporting lag may vary by stack",
    ],
    useCases: [
      "Marketing and lifecycle performance reporting",
      "Customer intelligence dashboards",
      "Executive reporting on engagement outcomes",
    ],
    integrations: ["Snowflake", "Hightouch", "Google Analytics"],
    bestFor: "Enterprise reporting and analytics",
    typicalUsers: "Analytics, marketing operations, and business teams",
  },
  "advertising-platforms": {
    id: "advertising-platforms",
    name: "Advertising Platforms",
    category: "analytics",
    categoryLabel: "Paid Media",
    purpose: "Audience activation and acquisition across paid media and advertising channels.",
    capabilities: [
      "Audience sync for acquisition",
      "Paid media campaign activation",
      "Lookalike and retargeting audiences",
      "Cross-channel ad delivery",
    ],
    strengths: [
      "Extends customer intelligence into acquisition",
      "Supports growth and demand generation",
      "Connects lifecycle data to paid media",
    ],
    limitations: [
      "Requires privacy and consent governance",
      "Not an owned-channel engagement platform",
      "Performance depends on audience quality",
    ],
    useCases: [
      "Retargeting and reactivation campaigns",
      "Lookalike acquisition programs",
      "Paid media audience activation from warehouse segments",
    ],
    integrations: ["Snowflake", "Hightouch", "Google Analytics"],
    bestFor: "Paid media audience activation",
    typicalUsers: "Growth, demand generation, and marketing analytics teams",
  },
  iterable: {
    id: "iterable",
    name: "Iterable",
    category: "engagement",
    purpose: "Cross-channel marketing platform focused on growth and lifecycle experimentation.",
    capabilities: [
      "Email and push campaigns",
      "Workflow Studio",
      "Experiments and A/B testing",
      "Catalog and personalisation",
      "SMS and in-app",
    ],
    strengths: [
      "Strong experimentation tooling",
      "Growth-team friendly UX",
      "Flexible workflow builder",
    ],
    limitations: [
      "Less enterprise CRM depth than Salesforce stack",
      "Warehouse activation usually needs middleware",
      "Complexity grows with journey count",
    ],
    useCases: [
      "Growth lifecycle programs",
      "Promotional campaign orchestration",
      "Product-led onboarding experiments",
    ],
    integrations: ["Segment", "Snowflake", "Hightouch", "Salesforce"],
    bestFor: "Growth and experimentation-led lifecycle teams",
    typicalUsers: "Growth marketing and CRM teams",
  },
  mparticle: {
    id: "mparticle",
    name: "mParticle",
    category: "cdp",
    purpose: "Enterprise customer data platform for real-time data collection and audience orchestration.",
    capabilities: [
      "Real-time event ingestion",
      "Audience segmentation",
      "Identity graph",
      "Partner integrations",
      "Data quality controls",
    ],
    strengths: [
      "Enterprise-grade CDP",
      "Strong mobile and app focus",
      "Real-time activation paths",
    ],
    limitations: [
      "Higher implementation overhead",
      "Premium pricing tier",
      "Requires cross-team alignment",
    ],
    useCases: [
      "Mobile-first customer data unification",
      "Real-time audience activation",
      "Cross-channel identity management",
    ],
    integrations: ["Braze", "Snowflake", "Salesforce", "Google Analytics"],
    bestFor: "Enterprise CDP and real-time activation",
    typicalUsers: "Enterprise marketing and data platform teams",
  },
  "google-analytics": {
    id: "google-analytics",
    name: "Google Analytics",
    category: "analytics",
    purpose: "Web and app analytics for understanding acquisition, behaviour, and conversion performance.",
    capabilities: [
      "Traffic analytics",
      "Conversion tracking",
      "Audience reporting",
      "Funnel analysis",
      "Campaign attribution",
    ],
    strengths: [
      "Ubiquitous web analytics standard",
      "Easy initial setup",
      "Strong marketing reporting",
    ],
    limitations: [
      "Limited warehouse-native depth",
      "Identity gaps across devices",
      "Not an activation platform",
    ],
    useCases: [
      "Website performance tracking",
      "Campaign measurement",
      "Top-of-funnel behaviour analysis",
    ],
    integrations: ["Segment", "Snowflake", "Braze", "Google Ads"],
    bestFor: "Digital analytics and acquisition reporting",
    typicalUsers: "Marketing analytics and growth teams",
  },
  mixpanel: {
    id: "mixpanel",
    name: "Mixpanel",
    category: "analytics",
    purpose: "Product analytics platform focused on user behaviour, retention, and funnel performance.",
    capabilities: [
      "Event-based analytics",
      "Retention analysis",
      "Funnel reporting",
      "Cohort exploration",
      "Experiment measurement",
    ],
    strengths: [
      "Product-team friendly analytics",
      "Strong behavioural insights",
      "Fast time-to-value for product teams",
    ],
    limitations: [
      "Not a messaging or CRM tool",
      "Warehouse integration varies by setup",
      "Requires disciplined event taxonomy",
    ],
    useCases: [
      "Feature adoption analysis",
      "Retention and churn diagnostics",
      "Experiment readouts",
    ],
    integrations: ["Segment", "Snowflake", "Braze", "Iterable"],
    bestFor: "Product-led growth analytics",
    typicalUsers: "Product managers and growth analysts",
  },
  customer: {
    id: "customer",
    name: "Customer",
    category: "customer",
    purpose: "End user or customer receiving personalized lifecycle experiences and communications.",
    capabilities: [
      "Receives email, push, SMS, and in-app messages",
      "Experiences onboarding and retention journeys",
      "Interacts with product and support touchpoints",
    ],
    strengths: [
      "Central outcome of the architecture",
      "Benefits from unified data and orchestration",
    ],
    limitations: [
      "Experience quality depends on upstream stack quality",
      "Fragmented data creates inconsistent journeys",
    ],
    useCases: [
      "Onboarding and activation",
      "Renewal and expansion",
      "Support and success engagement",
    ],
    integrations: ["All upstream platforms"],
    bestFor: "Delivering cohesive lifecycle experiences",
    typicalUsers: "Every customer and user of your product",
  },
};

export const platformList = Object.values(platforms);

export function getPlatform(id: string): Platform | undefined {
  return platforms[id];
}
