import type { Platform } from "./types";

export const platforms: Record<string, Platform> = {
  salesforce: {
    id: "salesforce",
    name: "Salesforce CRM",
    category: "crm",
    purpose: "System of record for customer relationships, sales pipeline, and account data.",
    capabilities: [
      "Account & contact management",
      "Opportunity tracking",
      "Sales automation",
      "Service cases",
      "Marketing Cloud connectors",
    ],
    strengths: [
      "Enterprise-grade CRM standard",
      "Rich ecosystem and AppExchange",
      "Deep sales and service workflows",
    ],
    limitations: [
      "Complex to configure at scale",
      "Data often siloed from warehouse analytics",
      "Lifecycle activation requires additional tools",
    ],
    useCases: [
      "B2B sales pipeline management",
      "Customer support case routing",
      "Account hierarchy and territory planning",
    ],
    integrations: ["Snowflake", "Segment", "Braze", "SFMC", "Hightouch"],
    bestFor: "Enterprise CRM and revenue operations",
    typicalUsers: "Sales, customer success, and RevOps teams",
  },
  snowflake: {
    id: "snowflake",
    name: "Snowflake",
    category: "warehouse",
    purpose: "Cloud data warehouse that centralises customer, product, and engagement data for analytics and activation.",
    capabilities: [
      "Unified data storage",
      "SQL analytics",
      "Secure data sharing",
      "Real-time data pipelines",
      "Role-based access control",
    ],
    strengths: [
      "Scales with enterprise data volume",
      "Separates storage and compute",
      "Strong partner ecosystem",
    ],
    limitations: [
      "Requires data modelling expertise",
      "Not a customer-facing activation layer",
      "Cost management needs governance",
    ],
    useCases: [
      "Customer 360 modelling",
      "Product usage analytics",
      "Churn and LTV scoring",
    ],
    integrations: ["Salesforce", "Hightouch", "Segment", "Braze", "OpenAI"],
    bestFor: "Modern analytics and data activation foundations",
    typicalUsers: "Data engineering, analytics, and lifecycle ops",
  },
  hightouch: {
    id: "hightouch",
    name: "Hightouch",
    category: "reverse-etl",
    purpose: "Reverse ETL platform that syncs warehouse data into engagement and operational tools.",
    capabilities: [
      "Audience syncing",
      "Reverse ETL pipelines",
      "Identity resolution helpers",
      "Journey triggers",
      "Operational workflows",
    ],
    strengths: [
      "Warehouse-native activation",
      "No duplicate data store required",
      "Strong martech integrations",
    ],
    limitations: [
      "Depends on clean warehouse models",
      "Not a messaging or CRM system",
      "Requires data team collaboration",
    ],
    useCases: [
      "Lifecycle segment activation",
      "Churn-risk audience sync",
      "Product usage triggers to Braze",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Iterable", "Segment"],
    bestFor: "Warehouse-to-martech orchestration",
    typicalUsers: "Lifecycle marketing and data teams",
  },
  braze: {
    id: "braze",
    name: "Braze",
    category: "engagement",
    purpose: "Customer engagement platform for orchestrating personalised lifecycle messaging across channels.",
    capabilities: [
      "Email",
      "Push notifications",
      "SMS",
      "In-app messaging",
      "Customer journeys",
      "Canvas orchestration",
    ],
    strengths: [
      "Modern journey builder",
      "Strong cross-channel orchestration",
      "Built for product-led lifecycle marketing",
    ],
    limitations: [
      "Requires quality audience data",
      "Complex journeys need governance",
      "Reporting often complemented by warehouse analytics",
    ],
    useCases: [
      "Onboarding journeys",
      "Feature adoption campaigns",
      "Retention and win-back programs",
    ],
    integrations: ["Snowflake", "Hightouch", "Segment", "OpenAI", "Salesforce"],
    bestFor: "Modern lifecycle marketing and engagement",
    typicalUsers: "Lifecycle marketers, CRM managers, product marketing",
  },
  sfmc: {
    id: "sfmc",
    name: "SFMC",
    category: "legacy-engagement",
    purpose: "Salesforce Marketing Cloud — enterprise marketing automation within the Salesforce ecosystem.",
    capabilities: [
      "Email Studio",
      "Journey Builder",
      "Mobile Studio",
      "Advertising Studio",
      "Data extensions",
    ],
    strengths: [
      "Deep Salesforce integration",
      "Enterprise marketing automation",
      "Familiar to Salesforce-centric orgs",
    ],
    limitations: [
      "Heavier implementation cycles",
      "Less agile than modern engagement platforms",
      "Data often trapped in Marketing Cloud silos",
    ],
    useCases: [
      "Enterprise email programs",
      "Salesforce-native customer journeys",
      "Regulated industry marketing",
    ],
    integrations: ["Salesforce CRM", "Snowflake", "MuleSoft"],
    bestFor: "Salesforce-native enterprise marketing",
    typicalUsers: "Enterprise marketing operations teams",
  },
  iterable: {
    id: "iterable",
    name: "Iterable",
    category: "engagement",
    purpose: "Cross-channel marketing platform focused on growth and lifecycle experimentation.",
    capabilities: [
      "Email and push campaigns",
      "Workflow Studio",
      "Experiments and A/B testing",
      "Catalog and personalisation",
      "SMS and in-app",
    ],
    strengths: [
      "Strong experimentation tooling",
      "Growth-team friendly UX",
      "Flexible workflow builder",
    ],
    limitations: [
      "Less enterprise CRM depth than Salesforce stack",
      "Warehouse activation usually needs middleware",
      "Complexity grows with journey count",
    ],
    useCases: [
      "Growth lifecycle programs",
      "Promotional campaign orchestration",
      "Product-led onboarding experiments",
    ],
    integrations: ["Segment", "Snowflake", "Hightouch", "Salesforce"],
    bestFor: "Growth and experimentation-led lifecycle teams",
    typicalUsers: "Growth marketing and CRM teams",
  },
  segment: {
    id: "segment",
    name: "Segment",
    category: "cdp",
    purpose: "Customer data platform that collects, cleans, and routes event data across the stack.",
    capabilities: [
      "Event collection",
      "Identity resolution",
      "Audience building",
      "Destination routing",
      "Protocol governance",
    ],
    strengths: [
      "Standardises event instrumentation",
      "Broad destination catalog",
      "Strong developer adoption",
    ],
    limitations: [
      "Can become costly at scale",
      "Not a warehouse replacement",
      "Requires disciplined tracking plans",
    ],
    useCases: [
      "Product analytics routing",
      "Real-time event forwarding",
      "Cross-tool identity stitching",
    ],
    integrations: ["Snowflake", "Braze", "Iterable", "Google Analytics", "Mixpanel"],
    bestFor: "Event collection and routing",
    typicalUsers: "Product, analytics, and growth engineering",
  },
  mparticle: {
    id: "mparticle",
    name: "mParticle",
    category: "cdp",
    purpose: "Enterprise customer data platform for real-time data collection and audience orchestration.",
    capabilities: [
      "Real-time event ingestion",
      "Audience segmentation",
      "Identity graph",
      "Partner integrations",
      "Data quality controls",
    ],
    strengths: [
      "Enterprise-grade CDP",
      "Strong mobile and app focus",
      "Real-time activation paths",
    ],
    limitations: [
      "Higher implementation overhead",
      "Premium pricing tier",
      "Requires cross-team alignment",
    ],
    useCases: [
      "Mobile-first customer data unification",
      "Real-time audience activation",
      "Cross-channel identity management",
    ],
    integrations: ["Braze", "Snowflake", "Salesforce", "Google Analytics"],
    bestFor: "Enterprise CDP and real-time activation",
    typicalUsers: "Enterprise marketing and data platform teams",
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    category: "ai",
    purpose: "AI models for content generation, classification, summarisation, and intelligent workflow assistance.",
    capabilities: [
      "LLM content generation",
      "Classification and tagging",
      "Summarisation",
      "Embeddings and retrieval",
      "Agent-style workflows",
    ],
    strengths: [
      "Broad model capability",
      "Strong ecosystem adoption",
      "Flexible API integration patterns",
    ],
    limitations: [
      "Requires guardrails and governance",
      "Not a data or messaging platform",
      "Quality depends on context and prompts",
    ],
    useCases: [
      "Personalised message drafting",
      "Journey content optimisation",
      "Support and lifecycle summarisation",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce", "Hightouch"],
    bestFor: "AI-assisted lifecycle content and intelligence",
    typicalUsers: "Product, lifecycle ops, and AI engineering teams",
  },
  claude: {
    id: "claude",
    name: "Claude",
    category: "ai",
    purpose: "AI assistant for reasoning-heavy tasks such as journey analysis, copy refinement, and operational insights.",
    capabilities: [
      "Long-context reasoning",
      "Structured analysis",
      "Content refinement",
      "Workflow assistance",
      "Document summarisation",
    ],
    strengths: [
      "Strong reasoning quality",
      "Useful for operational analysis",
      "Good for structured outputs",
    ],
    limitations: [
      "Requires integration layer",
      "Not a customer data system",
      "Needs human review in production workflows",
    ],
    useCases: [
      "Lifecycle strategy analysis",
      "Campaign copy refinement",
      "Operational playbook generation",
    ],
    integrations: ["Snowflake", "Braze", "Salesforce"],
    bestFor: "AI-assisted strategy and operations",
    typicalUsers: "Lifecycle leaders and marketing ops",
  },
  "google-analytics": {
    id: "google-analytics",
    name: "Google Analytics",
    category: "analytics",
    purpose: "Web and app analytics for understanding acquisition, behaviour, and conversion performance.",
    capabilities: [
      "Traffic analytics",
      "Conversion tracking",
      "Audience reporting",
      "Funnel analysis",
      "Campaign attribution",
    ],
    strengths: [
      "Ubiquitous web analytics standard",
      "Easy initial setup",
      "Strong marketing reporting",
    ],
    limitations: [
      "Limited warehouse-native depth",
      "Identity gaps across devices",
      "Not an activation platform",
    ],
    useCases: [
      "Website performance tracking",
      "Campaign measurement",
      "Top-of-funnel behaviour analysis",
    ],
    integrations: ["Segment", "Snowflake", "Braze", "Google Ads"],
    bestFor: "Digital analytics and acquisition reporting",
    typicalUsers: "Marketing analytics and growth teams",
  },
  mixpanel: {
    id: "mixpanel",
    name: "Mixpanel",
    category: "analytics",
    purpose: "Product analytics platform focused on user behaviour, retention, and funnel performance.",
    capabilities: [
      "Event-based analytics",
      "Retention analysis",
      "Funnel reporting",
      "Cohort exploration",
      "Experiment measurement",
    ],
    strengths: [
      "Product-team friendly analytics",
      "Strong behavioural insights",
      "Fast time-to-value for PMs",
    ],
    limitations: [
      "Not a messaging or CRM tool",
      "Warehouse integration varies by setup",
      "Requires disciplined event taxonomy",
    ],
    useCases: [
      "Feature adoption analysis",
      "Retention and churn diagnostics",
      "Experiment readouts",
    ],
    integrations: ["Segment", "Snowflake", "Braze", "Iterable"],
    bestFor: "Product-led growth analytics",
    typicalUsers: "Product managers and growth analysts",
  },
  customer: {
    id: "customer",
    name: "Customer",
    category: "customer",
    purpose: "The end recipient of personalised lifecycle experiences across channels and touchpoints.",
    capabilities: [
      "Receives email, push, SMS, and in-app messages",
      "Experiences onboarding and retention journeys",
      "Interacts with product and support touchpoints",
    ],
    strengths: [
      "Central outcome of the architecture",
      "Benefits from unified data and orchestration",
    ],
    limitations: [
      "Experience quality depends on upstream stack quality",
      "Fragmented data creates inconsistent journeys",
    ],
    useCases: [
      "Onboarding and activation",
      "Renewal and expansion",
      "Support and success engagement",
    ],
    integrations: ["All upstream platforms"],
    bestFor: "Delivering cohesive lifecycle experiences",
    typicalUsers: "Every customer and user of your product",
  },
};

export const platformList = Object.values(platforms);

export function getPlatform(id: string): Platform | undefined {
  return platforms[id];
}
